### ISSUE TITLE
Update dependencies inc babel

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-demo#120]
Babel is [7 is out](https://babeljs.io/docs/en/v7-migration) and the ecosystem around Webpack 4 has seemingly settled down. This seems like a good time to update our dependencies.

@ybiquitous You've updated a few dependencies recently, feel free to pick this up if you fancy it.

**Comment by ybiquitous** [comment]
OK! I'm interested in Babel 7, so I try it. 👍

**Comment by ybiquitous** [comment]
I opened a new PR #122. Please check it! 😆
