### ISSUE TITLE
Fix hidden syntax options on Windows

### ISSUE THREAD

**Issue by dramurai** [stylelint/stylelint-demo#139]
Font color for input syntax options in select box makes options invisible in dropdown.

**Chrome** 72.0.3626.81

![image](https://user-images.githubusercontent.com/2734983/52224611-b357c000-28a8-11e9-8a9f-ef4ad7ca9d9c.png)

**Microsoft Edge** 42.17134.1.0

![image](https://user-images.githubusercontent.com/2734983/52224657-d2eee880-28a8-11e9-991e-a61695cf774d.png)

OS Windows NT 10.0.17134

**Comment by jeddy3** [comment]
@dramurai Thanks for reporting this. I've created a quick PR to fix it, https://github.com/stylelint/stylelint-demo/pull/140.
