### ISSUE TITLE
Save CSS and rule configs

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint-demo#16]
After reading [stylelint/#2189](https://github.com/stylelint/stylelint/pull/2189) I wondered if there was anything else we could do to make the docs easier to understand. 

This is one suggestion - a new feature, which would allow the demo to be opened with preconfigured CSS and rules.

It can take some time for a new stylelint user to grok how the rules work together and how to appropriately configure the rules to match their preferred CSS style conventions. I see this feature as a useful tool to help with understanding stylelint configuration.

e.g. each of the various config and CSS snippets at [about-rules.md](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md) could link to a preconfigured demo. This would allow users to adjust the configs and CSS to see how the changes affect stylelint's output.

**Comment by jeddy3** [comment]
SGTM :)

**Comment by m-allanson** [comment]
Woohoo! Thank you @vankop and @hudochenkov, nice to see this issue closed out :)
