### ISSUE TITLE
Show line numbers and collapse json

### ISSUE THREAD

**Issue by chinesedfan** [stylelint/stylelint-demo#168]
They are my 2 suggestions for [Demo](https://stylelint.io/demo) page.

- Without line numbers for source codes, it is hard to find which line the error points to.
- With a better JSON editor, it will be easier to edit the stylelint config.

(Mistook opened in https://github.com/stylelint/stylelint.io/issues/81 at first)

**Comment by hudochenkov** [comment]
> Without line numbers for source codes, it is hard to find which line the error points to.

Actually, we showed line number, but one of patch updates of our dependency broke its. I've opened an issue https://github.com/satya164/react-simple-code-editor/issues/42

> With a better JSON editor, it will be easier to edit the stylelint config.

Could you elaborate on this?

**Comment by chinesedfan** [comment]
> With a better JSON editor, it will be easier to edit the stylelint config.

I mean adding something like showing dotted lines for levels and arrows to expand or collapse fields. Here is a sample.

![image](https://user-images.githubusercontent.com/1736154/63941569-7baba200-ca9e-11e9-9aab-f3c247f28b8e.png)

**Comment by hudochenkov** [comment]
I'm afraid it won't happen. Because it's a demo of stylelint, and not a demo of text editor. We're using simple and lightweight text editor with syntax highlighting: https://github.com/satya164/react-simple-code-editor It doesn't have these extra features.

**Comment by chinesedfan** [comment]
@hudochenkov Sure. Fixing line numbers is enough.
