### ISSUE TITLE
Investigate updating postcss-loader to v4+

### ISSUE THREAD

**Issue by mattxwang** [stylelint/stylelint-demo#237]
In #236, I realized that in updating `postcss-loader` to `v4+`, we'd need to install `postcss` as a peer dependency. This unleashed a bag of worms as there may be cross-compatability issues with `postcss-html` and possible issues with `postcss` versions 7 and 8. 

I suggest two approaches:

* first, is it possible to upgrade `postcss-loader` to version `4+` while adding `postcss` version `7`? if so, this should resolve the initial issue.
* if not, we can tack this on to the "upgrade to `postcss` 8" wishlist! it may involve circling back to `postcss-html` first, which I can also try to investigate

In addition, it was suggested to add a test for this type of error (broken HTML syntax), so we can catch it in the future. That could either be part of this solution, or a separate issue altogether!

**Comment by jeddy3** [comment]
> if not, we can tack this on to the "upgrade to postcss 8" wishlist! it may involve circling back to postcss-html first, which I can also try to investigate

This seems more likely.

> In addition, it was suggested to add a test for this type of error (broken HTML syntax), so we can catch it in the future.

Good shout. I believe we could do that as a separate pull request.

**Comment by ybiquitous** [comment]
FYI. We might need to update Webpack from v4 to v5 at the same time. See [this thread](https://github.com/stylelint/stylelint-demo/pull/245#discussion_r589272158).

**Comment by jeddy3** [comment]
Once we migrate stylelint to PostCSS@8 I think we'll be able to update all the dependencies to their latest versions, closing [the open pull requests](https://github.com/stylelint/stylelint-demo/pulls).
