### ISSUE TITLE
feat: deploy previews

### ISSUE THREAD

**Issue by mattxwang** [stylelint/stylelint-demo#260]
> What is the problem you're trying to solve?

Currently, testing new PRs is a bit tricky - we'd have to clone locally and test, and I know from a few PRs that I've merged-in that our current CI setup doesn't cover the entire production-facing featureset.

> What solution would you like to see?

It would be great if we could do a deploy preview for each pull request! Netlify has [free deploy previews for pull requests](https://docs.netlify.com/site-deploys/overview/#definitions), though this only works for static-ish websites (while the `stylelint-demo` also has a server). Unsure if there's a way we can do this efficiently with Heroku. Though, I'm not super familiar with the stack, so I may be missing something!

More than happy to look into this (since it's something I've had to do for my own projects / other nonprofit work), but curious to see what the rest of the stylelint team thinks!

**Comment by jeddy3** [comment]
Good idea.

Heroku has [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps). I've created a pipeline and enabled Review Apps. Hopefully, it'll show up on the next pull request.

**Comment by jeddy3** [comment]
Review apps are live.

See https://github.com/stylelint/stylelint-demo/pull/251 as an example

**Comment by mattxwang** [comment]
> Review apps are live.
> 
> See #251 as an example

Super cool, thanks for the quick turnaround!

**Comment by m-allanson** [comment]
Nice! 

If I ever get to finishing the 'stylelint in the browser' PR, we'd be able to simplify this repo a lot. It could possibly lead to removing this repo completely, and having the demo as 'just' another page on stylelint.io.
