### ISSUE TITLE
Display extra info from results object

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint-demo#27]
The demo only displays the `warnings` from a `result` object. It should also show `invalidOptionWarnings`, `deprecations` and `parseErrors`. 

See https://github.com/stylelint/stylelint/issues/2394#issuecomment-283696752

**Comment by fanich37** [comment]
Would like to work on this issue.
What should be entered to get ```deprecations``` and ```parseErrors``` warnings?

**Comment by hudochenkov** [comment]
Deprecations only shown if we set deprecation in core rule. Currently we don't have any deprecated rules. And `parseErrors` I don't even know. Because we apparently treat something as a `parseError`, and there are syntax errors, which are parse errors, but not `parseErrors` ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

Here's parse error, which is not `parseError`: https://stylelint.io/demo#N4Igxg9gJgpiBcID0SAEALGAbLEQBoQBnATwDsAXAQwA8FwiiDwIyAzASwHN7gAdMqlR8QAJwCuWGERHxU-QUOEgqFALQSpashDXiyAax0B3MrNQUJMAUIC+A2yFtA

**Comment by fanich37** [comment]
> we apparently treat something as a `parseError`, and there are syntax errors, which are parse errors, but not `parseErrors`

That's awesome 🤣 
So the only clear case to work on is the `invalidOptionWarnings`. I could add it if it's needed.

**Comment by hudochenkov** [comment]
Yeah, it would be great.

**Comment by jeddy3** [comment]
Good job with the `invalidOptionWarnings` PR!

> What should be entered to get [...] `parseErrors` warnings?

These are when one of the _construct-specific_ parsers throws an error i.e.:

- `postcss-media-query-parser`
- `postcss-selector-parser`
- `postcss-value-parser`

This usually means that the source was successfully parsed by one of [PostCSS syntaxes](https://github.com/postcss/postcss#syntaxes), but one of the _construct-specific_ parsers failed to parse either a media query, selector or value within that source.

Given the following config object:

```json
{
  "rules": {
    "selector-no-vendor-prefix": true,
  }
}
```

And this CSS:

```css
a:b(a:(f)) {}
```

The demo will render no errors whereas the CLI will show one:

```sconole
% echo "a:b(a:(f)) {}" | npx stylelint

<input css 1>
 1:1  ✖  Cannot parse selector   parseError
```

I hope that helps.

**Comment by jeddy3** [comment]
I think we can discount deprecations and close this issue when `parseErrors` are rendered.

**Comment by fanich37** [comment]
@jeddy3 Thank you for investigation and additional info. I'll check it ASAP!
