### ISSUE TITLE
Monaco Editor is tiny in Firefox

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint-demo#355]
### What steps are needed to reproduce the bug?

1. Open https://stylelint.io/demo/ in Firefox (I tested v112 and v113)
2. Monaco Editor is tiny (0px height) and tabs do not work

### What did you expect to happen?

Rendering in Chrome:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/115237/228379521-62aed226-da0e-431d-a102-6397992b370c.png">

### What actually happened?

Rendering in Firefox:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/115237/228379139-70402716-8eb9-4be6-8477-e2bf314b80b4.png">

**Comment by ybiquitous** [comment]
@silverwind Thanks for the report!

I've labeled the issue as **ready to implement**. Please consider contributing if you have time.
