### ISSUE TITLE
Add support for showing invalid rule options warnings

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint-demo#417]
### What steps are needed to reproduce the bug?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYLIBsICd45igG4UBfAHQDsQAaEAMwEtMYA5JAWzkRgA9OADiwB0YAM5ja4CJSYBzBCGBUUKciBwBXFmPXw0K1WunYcAWnqbKYAC6MZZyhBtI7MvSgDa6gEZIc6jQGlEZG6oxyTgQe3gwQEOoAuoaqpMkhZFSkUpCyEQBiuByuigBWYjJSsAKSiMoZ6mI2AJ4smIyUNh7qmK4wTYGGjS1tHTZmufJmTUiUUP5Q3SC9Nv1dIFkgpEA

### What did you expect to happen?

wavy underline under the option

### What actually happened?

`"✅ No problems!"`

**Comment by ybiquitous** [comment]
Thanks for the report! 👍🏼 

FYI, the "Invalid Option" errors are expectedly shown in CLI:

```sh-session
$ cat package.json
{
  "dependencies": {
    "stylelint": "^16.8.2"
  }
}

$ cat .stylelintrc.json
{
  "rules": {
    "color-function-notation": ["bar", {
      "ignore": ["foo"]
    }]
  }
}

$ echo '' | npx stylelint

Invalid Option: Invalid option value "bar" for rule "color-function-notation"
Invalid Option: Invalid value "foo" for option "ignore" of rule "color-function-notation"
```
