### ISSUE TITLE
Update `stylelintrc.json`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint-demo#433]
### Add

- [ ] ~~`validate`~~
- [x] `overrides.name`
- [x] `reportUnscopedDisables`
- [x] `ignoreFunctions` to `media-query-no-invalid`
- [x] `formatter`

**Comment by ybiquitous** [comment]
Sounds good. Let's try it. 👍🏼

**Comment by Mouvedia** [comment]
@ybiquitous some of these changes must be done after 16.11.0.

**Comment by Mouvedia** [comment]
WIP
