### ISSUE TITLE
`stylelintrc.json` should ignore namespaced rules

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint-demo#438]
### config tab

```json
{
  "plugins": "@stylistic/stylelint-plugin",
  "rules": {
    "@stylistic/string-quotes": "single"
  }
}
```

###

```
		"rules": {
			"properties": {
				"alpha-value-notation": {
				[…]
			},
			"patternProperties": {
              // TBD
			},
		}
```

ref https://json-schema.org/understanding-json-schema/reference/object#patternProperties

**Comment by ota-meshi** [comment]
Hmm... Is this an issue with the JSON schema registered in the Json Schema Store?
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/stylelintrc.json

**Comment by Mouvedia** [comment]
@ota-meshi

No it's not.
I just need to update https://github.com/stylelint/stylelint-demo/blob/main/src/schema/stylelintrc.json
I currently don't have time to check the pattern allowed for namespaces.
e.g. https://github.com/npm/validate-npm-package-name

Do we inherit npm scope restrictions?
i.e.

> - must be less than or equal to 214 characters
> - can begin with a dot or an underscore
> - can't contain any non-URL-safe characters
> - can't contain uppercase letters

**Comment by ota-meshi** [comment]
Oh, I didn't know I had that inside the project. Thank you for letting me know that 😅

**Comment by Mouvedia** [comment]
> Oh, I didn't know I had that inside the project.

It was a joint effort between @ybiquitous and me.
see #425

@ota-meshi can you add the _status: wip_ label?
